### PR TITLE
LRQA 68600

### PR DESCRIPTION
**Pull request by guivilarim**
[LRQA-68600](https://issues.liferay.com/browse/LRQA-68600)

### CODE REVIEW

**Comment by guivilarim** [comment]
ci:test:sf

**Comment by guivilarim** [comment]
ci:test:sf

**Comment by guivilarim** [comment]
ci:test:sf

**Comment by thaisfrota** [comment]
Forwarded: https://github.com/thaisfrota/liferay-portal/pull/24

**Pull request closed without merging**
