### PR TITLE
LRQA 69035

### PR DESCRIPTION
**Pull request by guivilarim**
[LRQA-69035](https://issues.liferay.com/browse/LRQA-69035)

### CODE REVIEW

**Comment by guivilarim** [comment]
ci:test:sf

**Comment by guivilarim** [comment]
ci:test:sf

**Comment by guivilarim** [comment]
ci:test:sf

**Comment by guivilarim** [comment]
ci:test:sf

**Comment by thaisfrota** [comment]
PR forwarded: https://github.com/thaisfrota/liferay-portal/pull/53

**Pull request closed without merging**
